# Generated by Django 6.1.1 on 2026-10-01 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text="Student's Full Name", max_length=200)),
                ('date_of_birth', models.DateField(blank=True, help_text='Date of birth', null=True)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('PREFER_NOT_TO_SAY', 'Prefer not to say')], max_length=25, null=True)),
                ('class_name', models.CharField(help_text='Class / Grade, e.g. 10, 11, 12', max_length=50)),
                ('section', models.CharField(blank=True, help_text='e.g. A, B, C', max_length=20, null=True)),
                ('school_name', models.CharField(db_index=True, help_text='Free text school name entered by student', max_length=255)),
                ('city', models.CharField(blank=True, help_text='City or Location', max_length=100, null=True)),
                ('interests_group', models.CharField(blank=True, help_text='Free text field, e.g. MPC, BiPC, Robotics, Design', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='parents.parent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
