# Generated by Django 6.1.1 on 2026-10-01 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('target_entity', models.CharField(max_length=100)),
                ('target_id', models.CharField(max_length=100)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_code', models.CharField(db_index=True, editable=False, help_text='Unique Registration Identifier e.g. D360-2026-000001', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('consent_given', models.BooleanField(default=True, help_text='Consent to terms and submission')),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes by administrator', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
