# Generated by Django 6.1.1 on 2026-10-01 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('WORKSHOP', 'Student Engagement Activity / Workshop'), ('CHALLENGE', 'Learning-Based Challenge'), ('COMPETITION', 'Competitions & Challenges'), ('CREATIVE', 'Creative Activities'), ('TEAM', 'Team-Based Activities'), ('PROBLEM_SOLVING', 'Problem-Solving Experience'), ('INTERACTIVE', 'Interactive Session')], default='WORKSHOP', max_length=50)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='events.event')),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['date', 'time'],
            },
        ),
    ]
