# Generated by Django 6.1.1 on 2026-10-01 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Parent or Guardian full name', max_length=200)),
                ('mobile', models.CharField(db_index=True, help_text='Contact mobile number', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Optional parent email', max_length=254, null=True)),
                ('relationship', models.CharField(blank=True, help_text='e.g. Father, Mother, Guardian', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
