# Generated by Django 6.1.1 on 2026-10-01 07:32

import certificates.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_code', models.CharField(db_index=True, default=certificates.models.generate_certificate_code, max_length=50, unique=True)),
                ('certificate_type', models.CharField(choices=[('PARTICIPATION', 'Participation Certificate'), ('ACHIEVEMENT', 'Achievement Certificate'), ('RECOGNITION', 'Recognition Certificate')], default='PARTICIPATION', max_length=30)),
                ('title', models.CharField(default='Certificate of Participation', max_length=255)),
                ('activity_name', models.CharField(blank=True, max_length=255, null=True)),
                ('issued_date', models.DateField(auto_now_add=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('verification_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='events.event')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='registrations.registration')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
